# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  tailscale_api_key: '{{ env.TAILSCALE_API_KEY }}',
  tailscale_org_id: '{{ env.TAILSCALE_ORG_ID }}'
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Tailscale'
    },
    user: {
      time_zone: Central Time (US & Canada),
      time_zone_iana: America/Chicago,
      utc_offset: -18000
    }
  }
