# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  tailscale_api_key: '{{ env.TAILSCALE_API_KEY }}',
  tailscale_org_id: '{{ env.TAILSCALE_ORG_ID }}'
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Tailscale'
    },
    user: {
      time_zone: Central Time (US & Canada),
      time_zone_iana: America/Chicago,
      utc_offset: -18000
    }
  }
  # IDX_1:
  #   devices:
  #     - name: Device Name 1
  #       addresses: [ 127.0.0.1 ]
  #       lastSeen: "2026-03-24T05:16:21Z"
  #       hostname: example1.local
  #       online: false
  #     - name: Device Name 2
  #       addresses: [ 127.0.0.2 ]
  #       lastSeen: "2026-03-24T05:16:21Z"
  #       hostname: example3.local
  #     - name: Device Name 3
  #       addresses: [ 127.0.0.3 ]
  #       lastSeen: "2025-03-24T05:16:21Z"
  #       hostname: example3.local
  #     - name: Device Name 4
  #       addresses: [ 127.0.0.4 ]
  #       lastSeen: "2026-03-24T05:16:21Z"
  #       hostname: example4.local
